Sports\Planning\GameAmountConfig:
  exclusion_policy: ALL
  exclude: false
  properties:
    amount:
      type: integer
  virtual_properties:
    getCompetitionSportId:
      type: integer
      serialized_name: competitionSportId