Sports\Planning\Config:
  exclusion_policy: ALL
  exclude: false
  properties:
    editMode:
      type: integer
    gamePlaceStrategy:
      type: SportsPlanning\Combinations\GamePlaceStrategy
    extension:
      type: boolean
    enableTime:
      type: boolean
    minutesPerGame:
      type: integer
    minutesPerGameExt:
      type: integer
    minutesAfter:
      type: integer
    minutesBetweenGames:
      type: integer
    selfReferee:
      type: SportsHelpers\SelfReferee