Sports\Planning\Config:
  exclusion_policy: ALL
  exclude: false
  properties:
    editMode:
      type: int
      access_type: public_method
      accessor:
        getter: getEditModeNative
        setter: setEditModeNative
    extension:
      type: boolean
    enableTime:
      type: boolean
    minutesPerGame:
      type: integer
    minutesPerGameExt:
      type: integer
    minutesAfter:
      type: integer
    minutesBetweenGames:
      type: integer
    perPoule:
      type: boolean
    selfReferee:
      type: int
      access_type: public_method
      accessor:
        getter: getSelfRefereeNative
        setter: setSelfRefereeNative