Sports\Planning\GameAmountConfig:
  exclusion_policy: ALL
  exclude: false
  properties:
    amount:
      type: integer
    partial:
      type: integer
    competitionSport:
      type: Sports\Competition\Sport