Sports\Planning\Config:
  exclusion_policy: ALL
  exclude: false
  properties:
    editMode:
    extension:
      type: boolean
    enableTime:
      type: boolean
    minutesPerGame:
      type: integer
    minutesPerGameExt:
      type: integer
    minutesAfter:
      type: integer
    minutesBetweenGames:
      type: integer
    perPoule:
      type: boolean
    selfReferee:
    nrOfSimSelfRefs:
      type: integer