Sports\Qualify\AgainstConfig:
  exclusion_policy: ALL
  exclude: false
  properties:
    winPoints:
      type: float
    drawPoints:
      type: float
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    losePointsExt:
      type: float
    pointsCalculation:
      type: int
      access_type: public_method
      accessor:
        getter: getPointsCalculationNative
        setter: setPointsCalculationNative
    competitionSport:
      type: Sports\Competition\Sport