Sports\Qualify\AgainstConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    winPoints:
      type: float
    drawPoints:
      type: float
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    losePointsExt:
      type: float
    pointsCalculation:
      type: integer
    sport:
      type: Sports\Sport