Sports\Score\Config:
  exclusion_policy: ALL
  exclude: false
  properties:
    direction:
      type: integer
    maximum:
      type: integer
    enabled:
      type: boolean
    next:
      type: Sports\Score\Config
  virtual_properties:
    getCompetitionSportId:
      type: integer
      serialized_name: competitionSportId