Sports\Sport\Config:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    winPoints:
      type: float
    drawPoints:
      type: float
    winPointsExt:
      type: float
    drawPointsExt:
      type: float
    losePointsExt:
      type: float
    pointsCalculation:
      type: integer
    nrOfGamePlaces:
      type: integer
    sport:
      type: Sports\Sport
    fields:
      type: ArrayCollection<Sports\Field>