Sports\Sport\ScoreConfig:
  exclusion_policy: ALL
  exclude: false
  properties:
    direction:
      type: integer
    maximum:
      type: integer
    enabled:
      type: boolean
    next:
      type: Sports\Sport\ScoreConfig
    competitionSportId:
      type: integer
  virtual_properties:
    getCompetitionSportId:
      type: integer
      serialized_name: competitionSportId