Sports\Sport\ScoreConfig:
  exclusion_policy: ALL
  exclude: false
  access_type: public_method

  properties:
    id:
      type: integer
    direction:
      type: integer
    maximum:
      type: integer
    enabled:
      type: boolean
    next:
      type: Sports\Sport\ScoreConfig
    sport:
      type: Sports\Sport